spring:
  redis:
    database: 0
    host: 58.247.132.78
    port: 6389
    password: Shcs123

  thymeleaf:
    mode: LEGACYHTML5
    cache: false

  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:/Volumes/APP/windlinker/src/main/db/myDb
    username: root
    password: root
