spring:
  redis:
    database: 0
    host: 192.168.3.103
    port: 6389
    password: Shcs123
    timeout: 8000
  jedis:
    host: 192.168.3.103
    password: Shcs123
    port: 6389
    timeout: 8000
    maxTotal: 15 # 最大连接数
    maxIdle: 10 # 最大空闲连接
    minIdle: 5 # 最小空闲连接
    maxWaitMillis: 10000 # 获取连接最大等待时间
    testOnBorrow: true # 获取连接时检测是否可用
  thymeleaf:
    mode: LEGACYHTML5
    cache: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://58.247.132.78:3306/mytestdb?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: Shcs2017@
    type: com.alibaba.druid.pool.DruidDataSource
